trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishedFilesArtifactName: 'publishFiles'

steps:
    - checkout: self
      displayName: Checkout repository

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'
        includePreviewVersions: true
    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build Assemblies'
      inputs:
        command: publish
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: CopyFiles@2
      displayName: Prepare services artifacts
      inputs:
        contents: "**"
        targetFolder: $(publishedFilesArtifactName)
        cleanTargetFolder: true

    - publish: $(publishedFilesArtifactName)
      artifact: $(publishedFilesArtifactName)
      displayName: Publish services artifacts